### ISSUE TITLE
Setup Heroku app.json

### ISSUE THREAD

**Issue by travismcchesney** [travismcchesney/github-pm#4]
**TODO:**
- [x] Create app.json
- [x] Include name, description, repository, keywords
- [x] Include environment variable for GitHub Organization name
